services:
  - type: web
    name: ivy-homes
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
    branch: master
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html