services:
  - type: web
    name: ivy-homes
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    branch: master
    healthCheckPath: /
    autoDeploy: true